#!/usr/bin/env bash

set -e -o pipefail

# utility function to download a file
function download {
  if [ -x "$(command -v wget)" ]; then
    wget -c -O "$2" "$1"
  elif [ -x "$(command -v curl)" ]; then
    curl -L "$1" >"$2"
  else
    echo "Can't figure out how to download from web.  Please install wget or curl." >&2
    exit 1
  fi
}

CVC_DIR=$(dirname $(dirname "$0"))
mkdir -p $CVC_DIR/deps
pushd $CVC_DIR/deps

BASE_DIR=`pwd`
mkdir -p $BASE_DIR/tmp/

##### Isabelle
ISABELLE_DIR="$BASE_DIR/isabelle"
mkdir -p $ISABELLE_DIR
ISABELLE_SETTINGS_DIR="$BASE_DIR/.isabelle"
mkdir -p $ISABELLE_SETTINGS_DIR

# Install dependencies
# Unfortunately running Isabelle with -Djava.awt.headles
apt-get update && apt-get install -y fontconfig fonts-dejavu


# download and unpack Isabelle
download "https://github.com/cvc5/isabelle-integration-evaluation/releases/download/IsabelleBinary/Isabelle.tar.gz" $BASE_DIR/tmp/Isabelle.tar.gz
tar --strip 1 -xvf $BASE_DIR/tmp/Isabelle.tar.gz -C $ISABELLE_DIR
rm $BASE_DIR/tmp/Isabelle.tar.gz

# build Isabelle
export USER_HOME="$BASE_DIR/"
export ISABELLE_HOME="$ISABELLE_DIR"
#Not sure if this one is needed
export ISABELLE_HOME_USER="$ISABELLE_DIR"

$ISABELLE_DIR/bin/isabelle components -a
$ISABELLE_DIR/bin/isabelle build Main
